### ISSUE TITLE
TConstruct Registered Castings Not Being Identified

### ISSUE THREAD

**Issue by ZACOyst** [SmithsModding/Weaponry#1]
I have noticed that when automatically generating recipes, Weaponry only seems to recognise materials that are native to TConstruct. For example, my game will generate an armor set for copper, but never for lead, despite lead having casting recipes for ingots from its liquid, and being registered to the ore dictionary as 'ingotLead'. The same is true for all the Thermal Foundation metals. 

I suspect that this is because, at the time that Weaponry does this task, the casting recipes have not yet been registered. Might it be possible to have this occur later in the initialization process to avoid this problem?

**Comment by marchermans** [comment]
I have to check... It currently happens in the post unit phase, which is basically the last init-phase of a mod. So I would need to find something that allows me to run the code after that.

I will investigate...

**Comment by ZACOyst** [comment]
Is there perhaps an event you can register to for each time a TiC casting recipe is added?

**Comment by marchermans** [comment]
I am looking right now :D

**Comment by marchermans** [comment]
This is going to be very complicated, yet I might have a way out. Give me some time to solve this.

**Comment by ZACOyst** [comment]
Hype!

**Comment by marchermans** [comment]
I have some bad news.....
Sadly enough without a rework of the way Armory works there is no way i can fix this....

The problem is that Armory requires the Data at a certain point during one of the init-phases. It posts an Event that tells other mods that it is looking for some data (being it new materials, or a property of a material that it is currently configuring, as well as the Icons and colors for the materials.

Currently there is no way around this problem, except for doing the initialization of the materials it self. Which is extremely hard todo, as i would have to find a point after the post-init (so outside of the standard FML init-system) todo it.

If you wnat Copper, Tin, Silver and/or lead support, add the Armory - World module to your pack. It will make sure that the materials are loaded in, the required WorldGen can be disabled in its Config file.

Greets,

SmithsModding

P.S.: If i find a way todo this better I will post it here.

**Comment by ZACOyst** [comment]
Ah well, thanks anyway for a really useful mod
